name: 'Gradle Build (non-master branch)'

on:
  push:
    branches-ignore: 
      - 'master'
      - 'gh-pages'

jobs:
  compile-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2
    - name: 'Set up JDK 11'
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: 'Grant execute permission for gradlew'
      run: chmod +x rust-lisa/gradlew
    - name: 'Gradle: compile and run unit tests'
      run: cd rust-lisa && ./gradlew test
