name: 'Gradle Build (master)'

on:
  push:
    branches: 
      - 'master'

jobs:
  build-and-cron:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # needed to have the tags below
    - name: 'Ensure git is installed'
      run: sudo apt-get install -y git
    - name: 'Set up JDK 11'
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: 'Grant execute permission for gradlew'
      run: chmod +x rust-lisa/gradlew
    - name: 'Gradle: full build and run cron tests'
      run: cd rust-lisa && ./gradlew build
